# Generated by Django 5.0.2 on 2024-06-29 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('atencion_poblacion', '0006_alter_atencionpoblacion_adjunto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='atencionpoblacion',
            old_name='carnet',
            new_name='ci',
        ),
    ]
