# Generated by Django 5.0.2 on 2024-06-29 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('atencion_poblacion', '0007_rename_carnet_atencionpoblacion_ci'),
    ]

    operations = [
        migrations.RenameField(
            model_name='atencionpoblacion',
            old_name='token',
            new_name='numero_seguimiento',
        ),
    ]
