# Generated by Django 5.0.2 on 2024-07-01 02:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('plataforma', '0006_alter_noticias_imagen_cabecera'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Gestor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('apellidos', models.CharField(max_length=150)),
                ('ci', models.CharField(max_length=11)),
                ('email', models.EmailField(max_length=50)),
                ('telefono', models.CharField(max_length=8)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tramite',
            fields=[
                ('tramitegeneral_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='plataforma.tramitegeneral')),
                ('numero_seguimiento', models.CharField(blank=True, max_length=36)),
                ('tipo_estudio', models.CharField(choices=[('Pregrado', 'Pregado')], default='', max_length=50)),
                ('tipo_est', models.CharField(choices=[('Posgrado', 'Posgrado')], default='', max_length=50)),
                ('uso', models.CharField(choices=[('Nacional', 'Nacional')], default='', max_length=50)),
                ('uso_i', models.CharField(choices=[('Internacional', 'Internacional')], default='', max_length=50)),
                ('nombre', models.CharField(max_length=150)),
                ('apellidos', models.CharField(max_length=150)),
                ('ci', models.CharField(max_length=11)),
                ('email', models.EmailField(max_length=50)),
                ('telefono', models.CharField(max_length=8)),
                ('tomo', models.CharField(max_length=4)),
                ('folio', models.CharField(max_length=4)),
                ('numero', models.CharField(max_length=4)),
                ('fecha', models.DateField(auto_now=True)),
                ('estado', models.CharField(choices=[('En Espera', 'En Espera'), ('Aceptado', 'Aceptado'), ('Procesando', 'Procesando'), ('Listo para Recoger', 'Listo para Recoger'), ('Entregado', 'Entregado'), ('Completado', 'Completado')], default='En Espera', max_length=100)),
                ('intereses', models.CharField(choices=[('Estatal', 'Estatal'), ('Particular', 'Particular')], default='Estatal', max_length=250)),
                ('organismo', models.CharField(blank=True, max_length=150, null=True)),
                ('organismo_op', models.CharField(choices=[('Consultoria Jurídica', 'Consultoria Jurídica'), ('Bufete Colectivo Internacional', 'Bufete Colectivo Internacional')], default='', max_length=250)),
                ('motivo', models.CharField(blank=True, max_length=250, null=True)),
                ('funcionario', models.CharField(max_length=50)),
                ('carrera', models.CharField(choices=[('Ing. Informática', 'Ing. Informática'), ('Ing. Industrial', 'Ing. Industrial'), ('Ing. Civil', 'Ing. Civil'), ('Ing. Mecánica', 'Ing. Mecánica')], max_length=50)),
                ('year', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default=1, max_length=50)),
                ('programa_academico', models.CharField(choices=[('Especialidad', 'Especialidad'), ('Maestría', 'Maestría'), ('Doctorado', 'Doctorado')], max_length=250)),
                ('nombre_programa', models.CharField(max_length=250)),
                ('tipo_pren', models.CharField(choices=[('Índice Académico', 'Índice Académico'), ('Certificación de Notas', 'Certificación de Notas'), ('Certifico de Estudios Terminados', 'Certifico de Estudios Terminados'), ('Copia Literal del Título', 'Copia Literal del Título')], max_length=50)),
                ('tipo_prei', models.CharField(choices=[('Índice Académico', 'Índice Académico'), ('Certificación de Notas', 'Certificación de Notas'), ('Certifico de Estudios Terminados', 'Certifico de Estudios Terminados'), ('Copia Literal del Título', 'Copia Literal del Título'), ('Plan de Estudio', 'Plan de Estudio'), ('Plan Temático', 'Plan Temático')], max_length=50)),
                ('tipo_posn', models.CharField(choices=[('Crédito Académico', 'Crédito Académico'), ('Certificación de Notas', 'Certificación de Notas'), ('Certifico de Estudios Terminados', 'Certifico de Estudios Terminados'), ('Copia Literal del Título', 'Copia Literal del Título')], max_length=50)),
                ('tipo_posi', models.CharField(choices=[('Crédito Académico', 'Crédito Académico'), ('Certificación de Notas', 'Certificación de Notas'), ('Certifico de Estudios Terminados', 'Certifico de Estudios Terminados'), ('Copia Literal del Título', 'Copia Literal del Título'), ('Plan de Estudio', 'Plan de Estudio'), ('Plan Temático', 'Plan Temático')], max_length=50)),
                ('legalizacion', models.CharField(default='Legalización de Foto Copia de Título', max_length=50)),
                ('archivo', models.FileField(upload_to='TramiteLegalizacion/')),
                ('gestor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='secretaria_docente.gestor')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'managed': True,
            },
            bases=('plataforma.tramitegeneral',),
        ),
    ]
