# Generated by Django 5.0.2 on 2024-07-01 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secretaria_docente', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tramite',
            name='gestor',
        ),
        migrations.DeleteModel(
            name='Gestor',
        ),
    ]
