# Generated by Django 5.0.2 on 2024-06-24 22:59

import plataforma.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.EmailField(max_length=254, unique=True)),
                ('smtp_server', models.CharField(max_length=255)),
                ('smtp_port', models.CharField(max_length=3)),
                ('smtp_username', models.CharField(max_length=255)),
                ('smtp_password', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='EstadosTramites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Noticias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('imagen_cabecera', models.ImageField(blank=True, null=True, upload_to='Noticias/24-06-2024/', validators=[plataforma.models.validate_file_extension])),
                ('resumen', models.CharField(blank=True, max_length=250, null=True)),
                ('cuerpo', models.TextField()),
                ('on_create', models.DateField(auto_now_add=True)),
                ('on_modified', models.DateField(auto_now=True)),
            ],
            options={
                'verbose_name': 'noticia',
                'verbose_name_plural': 'noticias',
            },
        ),
        migrations.CreateModel(
            name='TramiteGeneral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_tramite', models.CharField(max_length=250)),
                ('on_create', models.DateField(auto_now_add=True)),
                ('on_modified', models.DateField(auto_now=True)),
            ],
        ),
    ]
