# Generated by Django 5.0.2 on 2024-06-27 19:23

import plataforma.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0002_alter_noticias_imagen_cabecera'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticias',
            name='imagen_cabecera',
            field=models.ImageField(blank=True, null=True, upload_to='Noticias/27-06-2024/', validators=[plataforma.models.validate_file_extension]),
        ),
    ]
